export const UPDATE_SEARCH_TERM = "UPDATE_SEARCH_TERM";
export const UPDATE_PEOPLE = "UPDATE_PEOPLE";
export const UPDATE_PAGE = "UPDATE_PAGE";
export const UPDATE_COUNT = "UPDATE_COUNT";
export const UPDATE_VEHICLES = "UPDATE_VEHICLES";
export const SET_VEHICLE_URL = "SET_VEHICLE_URL";